### PR TITLE
add: expand mobile menu

### PR DESCRIPTION
**Pull request by Vierin**

### CODE REVIEW

**Comment by ihomp** [comment]
I think we need some UI updates for signed-in users. 
Screenshot 2024-06-04 at 04 03 23

The email doesn't "feel" clickable here. - That is access to the bithomp pro panel.

**Review by ihomp — CHANGES_REQUESTED** [review]
lets update signed-in ui

**Comment by Vierin** [comment]
I removed the opcity in the font so that the links don't look like they're not clickable. Also fixed offsets in links to xaman/bithomp pro user accounts when he is logged in.

**Comment by ihomp** [comment]
Screenshot 2024-06-17 at 06 14 29

Let's add an icon for Bithomp Pro (to align sign-in options better). @Anna15170221 had some suggestions or you can propose your own.

**Comment by ihomp** [comment]
@Anna15170221 can you pls test it locally, to make sure no menu items are missing on both xrpl mainnet and xahau

**Comment by Anna15170221** [comment]
Tested, everything seems fine.

**Review by ihomp — APPROVED** [review]

**Pull request merged**
