### PR TITLE
View toggler

### PR DESCRIPTION
**Pull request by Vierin**
Screenshot_2
Screenshot_3

### CODE REVIEW

**Comment by ihomp** [comment]
Screenshot 2024-06-17 at 05 47 43
Screenshot 2024-06-17 at 05 47 31
Screenshot 2024-06-17 at 05 47 18

may it can always have its own space, like in the view when there filters are hidden.

Screenshot 2024-06-17 at 05 50 12

**Review by ihomp — CHANGES_REQUESTED** [review]
let's give a permanent space for the line with view toggle (later sorting will be added there also)

**Comment by Vierin** [comment]
I added a wrapper for filters navigation (where there will be a view toggler and a sorting list) and increased the indentation at the top.

Screenshot_2

**Review by ihomp — APPROVED** [review]
Looks good, thx

**Pull request merged**
